### ISSUE TITLE
Where can I declare x?

### ISSUE THREAD

**Issue by conan19842002** [mwshinn/PyDDM#35] opened 2021-04-14 08:16 UTC
Can you let me know how I can declare x domain? there are only parameters for dt, dx and T but not x.

**Comment by mwshinn** [comment] 2021-04-14 08:21
You don't declare the x domain.  X domain is constructed from your bound height divided by dx.

This is not a bug, so I am closing the issue.

**Closed by mwshinn** 2021-04-14 08:21 UTC
