### ISSUE TITLE
Could you help me with defining race model i.e., how to implement multiple accumulators?

### ISSUE THREAD

**Issue by vaibrainium** [mwshinn/PyDDM#38] opened 2021-04-30 22:00 UTC

**Comment by mwshinn** [comment] 2021-05-01 05:42
Unfortunately, PyDDM does not support multiple accumulators.

I am closing this because it is not a bug.  In the future, know that a bug tracker is not the right place to ask questions.  The [discussion board](https://github.com/mwshinn/PyDDM/discussions) is a better place for this.  In fact, [this question has already been asked on the discussion board](https://github.com/mwshinn/PyDDM/discussions/37)!

**Closed by mwshinn** 2021-05-01 05:42 UTC
